import Footer from '@/components/header-footer/footer'
import Header from '@/components/header-footer/header'
import '@/styles/globals.css'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

function App({ Component, pageProps }) {

  const router = useRouter();

  const [categoryList, setCategoryList] = useState([]);

  useEffect(() => {
    if (window.location.pathname != '/') {
      let container = document.querySelector("header .container");
      let footerContainer = document.querySelector("footer .container");
      [container, footerContainer].forEach((elem) => {
        elem?.classList.replace("container", "big_container");
      })
    }

    getInitialData();

  }, [])

  const getInitialData = async () => {
    
    let categoryList = await fetch(`${process.env.NEXT_PUBLIC_BASEURL}/category`, {
      method: "GET"
    }).then(response => response.json());

    // get product list

    setCategoryList(categoryList.data.data);
  }

  return (
    <>
      <Head>
        <title>Template Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {
        router.pathname == '/register' || router.pathname == '/login' || router.pathname == '/enterOtp' || router.pathname == '/resetPassword' || router.pathname == '/forgotPassword' ?
          <>
          </>
          :

          <Header categoryList={ categoryList } />
      }
      <Component {...pageProps} />
      {router.pathname == '/register' || router.pathname == '/login' || router.pathname == '/enterOtp' || router.pathname == '/resetPassword' || router.pathname == '/forgotPassword' ?
        <> </>
        :
        <Footer />
      }
    </>
  )

}

export default App;