import Footer from '@/components/header-footer/footer'
import Header from '@/components/header-footer/header'
import '@/styles/globals.css'
import Head from 'next/head'
import { useEffect } from 'react'

export default function App({ Component, pageProps }) {

  // replacing the class container to big_container bcz of all pages contains big container excepct landing page.
  useEffect(() => {
    if (window.location.pathname != '/') {
      let container = document.querySelector("header .container");
      let footerContainer = document.querySelector("footer .container");
      [container, footerContainer].forEach((elem) => {
        elem?.classList.replace("container", "big_container");
      })
    }
  }, [])

  return (
    <>
      <Head>
        <title>Template Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </>
  )

}
